export const CURRENCIES = [
  { code: 'IDR', label: 'Indonesian Rupiah' },
  { code: 'USD', label: 'US Dollar' },
  { code: 'EUR', label: 'Euro' },
  { code: 'GBP', label: 'British Pound' },
  { code: 'JPY', label: 'Japanese Yen' },
  { code: 'AUD', label: 'Australian Dollar' },
  { code: 'CAD', label: 'Canadian Dollar' },
  { code: 'CHF', label: 'Swiss Franc' },
  { code: 'CNY', label: 'Chinese Yuan' },
  { code: 'HKD', label: 'Hong Kong Dollar' },
  { code: 'SGD', label: 'Singapore Dollar' },
  { code: 'KRW', label: 'South Korean Won' },
  { code: 'INR', label: 'Indian Rupee' },
  { code: 'MYR', label: 'Malaysian Ringgit' },
  { code: 'THB', label: 'Thai Baht' },
  { code: 'PHP', label: 'Philippine Peso' },
  { code: 'VND', label: 'Vietnamese Dong' },
  { code: 'SAR', label: 'Saudi Riyal' },
  { code: 'AED', label: 'UAE Dirham' },
  { code: 'BRL', label: 'Brazilian Real' },
  { code: 'MXN', label: 'Mexican Peso' },
  { code: 'ZAR', label: 'South African Rand' },
  { code: 'NZD', label: 'New Zealand Dollar' },
  { code: 'SEK', label: 'Swedish Krona' },
  { code: 'NOK', label: 'Norwegian Krone' },
  { code: 'DKK', label: 'Danish Krone' },
  { code: 'PLN', label: 'Polish Zloty' },
  { code: 'TWD', label: 'New Taiwan Dollar' },
  { code: 'TRY', label: 'Turkish Lira' },
  { code: 'RUB', label: 'Russian Ruble' },
  { code: 'ARS', label: 'Argentine Peso' },
  { code: 'CLP', label: 'Chilean Peso' },
  { code: 'COP', label: 'Colombian Peso' },
  { code: 'PEN', label: 'Peruvian Sol' },
  { code: 'EGP', label: 'Egyptian Pound' },
  { code: 'NGN', label: 'Nigerian Naira' },
  { code: 'KES', label: 'Kenyan Shilling' },
  { code: 'GHS', label: 'Ghanaian Cedi' },
  { code: 'PKR', label: 'Pakistani Rupee' },
  { code: 'BDT', label: 'Bangladeshi Taka' },
  { code: 'LKR', label: 'Sri Lankan Rupee' },
  { code: 'MAD', label: 'Moroccan Dirham' },
  { code: 'DZD', label: 'Algerian Dinar' },
  { code: 'QAR', label: 'Qatari Riyal' },
  { code: 'KWD', label: 'Kuwaiti Dinar' },
  { code: 'BHD', label: 'Bahraini Dinar' },
  { code: 'OMR', label: 'Omani Rial' },
  { code: 'JOD', label: 'Jordanian Dinar' },
  { code: 'LBP', label: 'Lebanese Pound' },
  { code: 'ILS', label: 'Israeli New Shekel' }
];
